# Generated by Django 5.1.1 on 2024-10-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='Videos/'),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='video_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
