# Generated by Django 5.1.2 on 2024-10-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postted_by',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
