# Generated by Django 5.1.2 on 2024-10-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_postted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postted_by',
            new_name='posted_by',
        ),
    ]
