# Generated by Django 5.1.2 on 2024-10-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_postted_by_comment_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(max_length=100),
        ),
    ]
